import type {
  AttendanceRecord,
  NewsEvent,
  SportSection,
  TeacherGroup,
  TeacherReport,
  WeeklyAttendance,
} from "@/lib/types";

export const SELECTION_PERIOD_OPEN = true;
export const SELECTION_END = "2026-09-30";
export const TEACHER_NAME = "Мартин М. М.";

export const SECTIONS: SportSection[] = [
  {
    id: "powerlifting",
    name: { ru: "Пауэрлифтинг", fr: "Powerlifting", en: "Powerlifting" },
    sport: "powerlifting",
    category: "individual",
    teacher: "Иванов И. И.",
    description: {
      ru: "Силовая подготовка: приседания, жим лёжа, становая тяга.",
      fr: "Force athlétique : squat, développé couché, soulevé de terre.",
      en: "Strength training: squat, bench press, deadlift.",
    },
    capacity: 20,
    enrolled: 10,
    enrollmentOpen: true,
    sessions: [
      {
        day: "tuesday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
      },
      {
        day: "thursday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
      },
    ],
  },
  {
    id: "swimming",
    name: { ru: "Плавание", fr: "Natation", en: "Swimming" },
    sport: "swimming",
    category: "individual",
    teacher: "Смирнова А. А.",
    description: {
      ru: "Техника плавания кролем и брассом, тренировки в бассейне.",
      fr: "Technique de nage libre et brasse, entraînements en piscine.",
      en: "Freestyle and breaststroke technique, pool training.",
    },
    capacity: 18,
    enrolled: 8,
    enrollmentOpen: true,
    sessions: [
      {
        day: "wednesday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Бассейн", fr: "Piscine", en: "Pool" },
      },
      {
        day: "friday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Бассейн", fr: "Piscine", en: "Pool" },
      },
    ],
  },
  {
    id: "chess",
    name: { ru: "Шахматы", fr: "Échecs", en: "Chess" },
    sport: "chess",
    category: "individual",
    teacher: "Петров С. С.",
    description: {
      ru: "Дебюты, тактика, разбор партий и турнирная практика.",
      fr: "Ouvertures, tactique, analyse de parties et pratique du tournoi.",
      en: "Openings, tactics, game analysis and tournament practice.",
    },
    capacity: 16,
    enrolled: 6,
    enrollmentOpen: true,
    sessions: [
      {
        day: "monday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Клубный зал", fr: "Salle du club", en: "Club room" },
      },
    ],
  },
  {
    id: "football",
    name: { ru: "Футбол", fr: "Football", en: "Football" },
    sport: "football",
    category: "team",
    teacher: "Кузнецов А. В.",
    description: {
      ru: "Командные тренировки, техника и тактика игры.",
      fr: "Entraînements collectifs, technique et tactique du jeu.",
      en: "Team training, technique and game tactics.",
    },
    capacity: 30,
    enrolled: 22,
    enrollmentOpen: true,
    sessions: [
      {
        day: "tuesday",
        start: "18:00",
        end: "20:00",
        location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
      },
      {
        day: "thursday",
        start: "18:00",
        end: "20:00",
        location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
      },
    ],
  },
  {
    id: "sambo",
    name: { ru: "Самбо", fr: "Sambo", en: "Sambo" },
    sport: "sambo",
    category: "combat",
    teacher: "Алексеев В. В.",
    description: {
      ru: "Борьба в стойке и партере, броски и приёмы.",
      fr: "Lutte debout et au sol, projections et techniques.",
      en: "Stand-up and ground wrestling, throws and techniques.",
    },
    capacity: 15,
    enrolled: 10,
    enrollmentOpen: true,
    sessions: [
      {
        day: "wednesday",
        start: "18:00",
        end: "20:00",
        location: { ru: "Зал борьбы", fr: "Salle de lutte", en: "Wrestling hall" },
      },
    ],
  },
  {
    id: "judo",
    name: { ru: "Дзюдо", fr: "Judo", en: "Judo" },
    sport: "judo",
    category: "combat",
    teacher: "Львова О. О.",
    description: {
      ru: "Бросковая техника, удержания и спарринги.",
      fr: "Techniques de projection, immobilisations et combats.",
      en: "Throwing techniques, pins and sparring.",
    },
    capacity: 14,
    enrolled: 7,
    enrollmentOpen: true,
    sessions: [
      {
        day: "monday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Зал борьбы", fr: "Salle de lutte", en: "Wrestling hall" },
      },
    ],
  },
  {
    id: "hockey",
    name: { ru: "Хоккей", fr: "Hockey", en: "Ice hockey" },
    sport: "hockey",
    category: "team",
    teacher: "Громов С. С.",
    description: {
      ru: "Катание, техника владения клюшкой, командная игра.",
      fr: "Patinage, maniement de la crosse et jeu collectif.",
      en: "Skating, stick handling and team play.",
    },
    capacity: 20,
    enrolled: 13,
    enrollmentOpen: true,
    sessions: [
      {
        day: "saturday",
        start: "12:00",
        end: "14:00",
        location: { ru: "Ледовая арена", fr: "Patinoire", en: "Ice rink" },
      },
    ],
  },
  {
    id: "athletics",
    name: { ru: "Лёгкая атлетика", fr: "Athlétisme", en: "Athletics" },
    sport: "athletics",
    category: "individual",
    teacher: "Сорокин М. М.",
    description: {
      ru: "Бег на короткие и средние дистанции, ОФП.",
      fr: "Course courte et moyenne distance, condition physique.",
      en: "Sprint and middle distance running, general fitness.",
    },
    capacity: 25,
    enrolled: 16,
    enrollmentOpen: true,
    sessions: [
      {
        day: "friday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
      },
    ],
  },
  {
    id: "tennis",
    name: { ru: "Большой теннис", fr: "Tennis", en: "Tennis" },
    sport: "tennis",
    category: "individual",
    teacher: "Романова Е. Е.",
    description: {
      ru: "Удары с отскока и с лёта, подача, парные игры.",
      fr: "Coups de fond et volées, service, double.",
      en: "Groundstrokes, volleys, serve and doubles play.",
    },
    capacity: 12,
    enrolled: 6,
    enrollmentOpen: true,
    sessions: [
      {
        day: "sunday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Теннисные корты", fr: "Courts de tennis", en: "Tennis courts" },
      },
    ],
  },
  {
    id: "tabletennis",
    name: { ru: "Настольный теннис", fr: "Tennis de table", en: "Table tennis" },
    sport: "tabletennis",
    category: "individual",
    teacher: "Егоров С. С.",
    description: {
      ru: "Техника ударов, подачи и наработка реакции.",
      fr: "Technique des coups, services et travail de la réactivité.",
      en: "Stroke technique, serves and reaction training.",
    },
    capacity: 10,
    enrolled: 4,
    enrollmentOpen: true,
    sessions: [
      {
        day: "tuesday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Зал настольного тенниса", fr: "Salle de tennis de table", en: "Table tennis hall" },
      },
    ],
  },
  {
    id: "armwrestling",
    name: { ru: "Армрестлинг", fr: "Armlutte", en: "Armwrestling" },
    sport: "armwrestling",
    category: "individual",
    teacher: "Новиков Д. Д.",
    description: {
      ru: "Сила хвата и плечевого пояса, техника борьбы за столом.",
      fr: "Force de préhension et de l'épaule, technique de combat de bras.",
      en: "Grip and shoulder strength, table technique.",
    },
    capacity: 10,
    enrolled: 4,
    enrollmentOpen: true,
    sessions: [
      {
        day: "thursday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
      },
    ],
  },
  {
    id: "basketball",
    name: { ru: "Баскетбол", fr: "Basketball", en: "Basketball" },
    sport: "basketball",
    category: "team",
    teacher: "Мартин М. М.",
    description: {
      ru: "Дриблинг, броски и командная тактика для новичков.",
      fr: "Dribble, tirs et tactique collective pour débutants.",
      en: "Dribbling, shooting and team tactics for beginners.",
    },
    capacity: 20,
    enrolled: 15,
    enrollmentOpen: true,
    sessions: [
      {
        day: "monday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Спортивный зал A", fr: "Gymnase A", en: "Gym A" },
      },
      {
        day: "wednesday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Спортивный зал A", fr: "Gymnase A", en: "Gym A" },
      },
    ],
  },
  {
    id: "golf",
    name: { ru: "Гольф", fr: "Golf", en: "Golf" },
    sport: "golf",
    category: "individual",
    teacher: "Куликов П. П.",
    description: {
      ru: "Техника ударов, короткая игра и правила гольфа.",
      fr: "Technique de swing, petit jeu et règles du golf.",
      en: "Swing technique, short game and rules of golf.",
    },
    capacity: 8,
    enrolled: 3,
    enrollmentOpen: true,
    sessions: [
      {
        day: "saturday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Гольф-клуб", fr: "Golf-club", en: "Golf club" },
      },
    ],
  },
  {
    id: "karate",
    name: { ru: "Каратэ", fr: "Karaté", en: "Karate" },
    sport: "karate",
    category: "combat",
    teacher: "Волкова Т. Т.",
    description: {
      ru: "Ката, удары руками и ногами, базовая техника.",
      fr: "Katas, frappes poings et pieds, technique de base.",
      en: "Katas, hand and foot strikes, basic technique.",
    },
    capacity: 12,
    enrolled: 7,
    enrollmentOpen: true,
    sessions: [
      {
        day: "wednesday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Зал единоборств", fr: "Salle d'arts martiaux", en: "Martial arts hall" },
      },
    ],
  },
  {
    id: "boxing",
    name: { ru: "Бокс", fr: "Boxe", en: "Boxing" },
    sport: "boxing",
    category: "combat",
    teacher: "Галкин А. А.",
    description: {
      ru: "Работа ног, серии ударов и работа в парах на ринге.",
      fr: "Jeu de jambes, enchaînements et travail en binôme sur ring.",
      en: "Footwork, combinations and pair work in the ring.",
    },
    capacity: 15,
    enrolled: 9,
    enrollmentOpen: true,
    sessions: [
      {
        day: "friday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Ринг", fr: "Ring", en: "Ring" },
      },
    ],
  },
];

export const NEWS: NewsEvent[] = [
  {
    id: "n1",
    title: {
      ru: "Финал чемпионата по баскетболу",
      fr: "Finale du championnat de basketball",
      en: "Basketball championship final",
    },
    date: "2026-08-05",
    time: "18:00",
    location: { ru: "Спортивный зал №1", fr: "Gymnase n°1", en: "Gym No. 1" },
    sport: "basketball",
    status: "upcoming",
  },
  {
    id: "n2",
    title: {
      ru: "Открытый турнир по плаванию",
      fr: "Tournoi ouvert de natation",
      en: "Open swimming tournament",
    },
    date: "2026-08-08",
    time: "10:00",
    location: { ru: "Бассейн", fr: "Piscine", en: "Pool" },
    sport: "swimming",
    status: "upcoming",
  },
  {
    id: "n3",
    title: {
      ru: "Футбольный матч: МИСИС против МГУ",
      fr: "Match de football : MISIS contre MGU",
      en: "Football match: MISIS vs MGU",
    },
    date: "2026-08-12",
    time: "19:30",
    location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
    sport: "football",
    status: "upcoming",
  },
  {
    id: "n4",
    title: {
      ru: "Теннисный турнир среди студентов",
      fr: "Tournoi de tennis étudiant",
      en: "Student tennis tournament",
    },
    date: "2026-08-15",
    time: "14:00",
    location: { ru: "Теннисные корты", fr: "Courts de tennis", en: "Tennis courts" },
    sport: "tennis",
    status: "upcoming",
  },
  {
    id: "n5",
    title: {
      ru: "Чемпионат по пауэрлифтингу",
      fr: "Championnat de powerlifting",
      en: "Powerlifting championship",
    },
    date: "2026-08-19",
    time: "11:00",
    location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
    sport: "powerlifting",
    status: "upcoming",
  },
  {
    id: "n6",
    title: {
      ru: "Волейбольный турнир: победа 3:1",
      fr: "Tournoi de volleyball : victoire 3:1",
      en: "Volleyball tournament: win 3:1",
    },
    date: "2026-07-28",
    time: "17:00",
    location: { ru: "Спортивный зал №2", fr: "Gymnase n°2", en: "Gym No. 2" },
    sport: "football",
    status: "past",
  },
  {
    id: "n7",
    title: {
      ru: "Кросс-кантри забег завершён",
      fr: "Course de cross-country terminée",
      en: "Cross-country run completed",
    },
    date: "2026-07-24",
    time: "09:00",
    location: { ru: "Парк", fr: "Parc", en: "Park" },
    sport: "athletics",
    status: "past",
  },
  {
    id: "n8",
    title: {
      ru: "Шахматный блиц-турнир",
      fr: "Tournoi blitz d'échecs",
      en: "Chess blitz tournament",
    },
    date: "2026-07-18",
    time: "15:00",
    location: { ru: "Клубный зал", fr: "Salle du club", en: "Club room" },
    sport: "chess",
    status: "past",
  },
];

export const ATTENDANCE: AttendanceRecord[] = [
  {
    id: "a1",
    date: "2026-07-06",
    section: "basketball",
    present: true,
    notes: { ru: "Отличная тренировка", fr: "Excellent entraînement", en: "Great workout" },
  },
  {
    id: "a2",
    date: "2026-07-08",
    section: "basketball",
    present: true,
    notes: { ru: "Работа над броском", fr: "Travail du tir", en: "Shooting practice" },
  },
  {
    id: "a3",
    date: "2026-07-13",
    section: "swimming",
    present: false,
    notes: { ru: "Пропуск по уважительной причине", fr: "Absence justifiée", en: "Excused absence" },
  },
  {
    id: "a4",
    date: "2026-07-15",
    section: "basketball",
    present: true,
    notes: { ru: "Лучший результат 85 кг", fr: "Meilleure performance 85 kg", en: "Personal best 85 kg" },
  },
  {
    id: "a5",
    date: "2026-07-20",
    section: "athletics",
    present: true,
    notes: { ru: "Новая дистанция 100 м", fr: "Nouvelle distance 100 m", en: "New distance 100 m" },
  },
  {
    id: "a6",
    date: "2026-07-22",
    section: "basketball",
    present: true,
    notes: { ru: "Тактическая работа", fr: "Travail tactique", en: "Tactical work" },
  },
  {
    id: "a7",
    date: "2026-07-27",
    section: "basketball",
    present: false,
    notes: { ru: "Болел", fr: "Malade", en: "Sick" },
  },
  {
    id: "a8",
    date: "2026-07-29",
    section: "basketball",
    present: true,
    notes: { ru: "Подготовка к турниру", fr: "Préparation du tournoi", en: "Tournament preparation" },
  },
];

export const WEEKLY_ATTENDANCE: WeeklyAttendance[] = [
  { weekStart: "2026-06-08", attended: 3, total: 4 },
  { weekStart: "2026-06-15", attended: 2, total: 4 },
  { weekStart: "2026-06-22", attended: 4, total: 4 },
  { weekStart: "2026-06-29", attended: 3, total: 4 },
  { weekStart: "2026-07-06", attended: 4, total: 4 },
  { weekStart: "2026-07-13", attended: 3, total: 4 },
  { weekStart: "2026-07-20", attended: 4, total: 4 },
  { weekStart: "2026-07-27", attended: 2, total: 3 },
];

export const TEACHER_GROUPS: TeacherGroup[] = [
  {
    id: "g1",
    name: { ru: "Баскетбол — начинающие", fr: "Basketball — débutants", en: "Basketball — beginners" },
    level: { ru: "Начальный", fr: "Débutant", en: "Beginner" },
    students: 15,
    sessions: [
      {
        day: "monday",
        start: "16:00",
        end: "18:00",
        location: { ru: "Спортивный зал A", fr: "Gymnase A", en: "Gym A" },
      },
      {
        day: "wednesday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Спортивный зал A", fr: "Gymnase A", en: "Gym A" },
      },
    ],
    members: [
      "Иванов Д. А.",
      "Петрова К. С.",
      "Сидорова А. В.",
      "Кузнецов М. И.",
      "Смирнов Н. П.",
      "Фёдорова О. Ю.",
      "Волков Е. А.",
      "Козлова Д. Р.",
    ],
  },
  {
    id: "g2",
    name: { ru: "Футбол — соревновательный", fr: "Football — compétition", en: "Football — competitive" },
    level: { ru: "Соревновательный", fr: "Compétition", en: "Competitive" },
    students: 22,
    sessions: [
      {
        day: "tuesday",
        start: "18:00",
        end: "20:00",
        location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
      },
      {
        day: "thursday",
        start: "18:00",
        end: "20:00",
        location: { ru: "Стадион", fr: "Stade", en: "Stadium" },
      },
    ],
    members: [
      "Андреев С. В.",
      "Борисов И. О.",
      "Васильев А. С.",
      "Громов П. А.",
      "Дмитриев К. М.",
      "Егоров Р. И.",
      "Жуков Т. Д.",
      "Захаров Ю. Е.",
    ],
  },
  {
    id: "g3",
    name: { ru: "Плавание — группа 1", fr: "Natation — groupe 1", en: "Swimming — group 1" },
    level: { ru: "Начальный", fr: "Débutant", en: "Beginner" },
    students: 12,
    sessions: [
      {
        day: "wednesday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Бассейн", fr: "Piscine", en: "Pool" },
      },
      {
        day: "friday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Бассейн", fr: "Piscine", en: "Pool" },
      },
    ],
    members: [
      "Кириллова А. С.",
      "Лапин М. Д.",
      "Морозова В. А.",
      "Никитин П. Р.",
      "Орлов Г. И.",
      "Павлова Т. М.",
    ],
  },
  {
    id: "g4",
    name: { ru: "Пауэрлифтинг — основы", fr: "Powerlifting — bases", en: "Powerlifting — basics" },
    level: { ru: "Начальный", fr: "Débutant", en: "Beginner" },
    students: 9,
    sessions: [
      {
        day: "tuesday",
        start: "10:00",
        end: "12:00",
        location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
      },
      {
        day: "thursday",
        start: "14:00",
        end: "16:00",
        location: { ru: "Зал силовой подготовки", fr: "Salle de musculation", en: "Weight room" },
      },
    ],
    members: [
      "Романова Е. Е.",
      "Соболев Д. В.",
      "Тарасов И. К.",
      "Ульянова М. Г.",
      "Филиппов Н. Н.",
    ],
  },
];

export const TEACHER_REPORTS: TeacherReport[] = [
  {
    id: "r1",
    date: "2026-07-27",
    group: { ru: "Баскетбол — начинающие", fr: "Basketball — débutants", en: "Basketball — beginners" },
    present: 14,
    absent: 1,
    notes: { ru: "Отрабатывали броски со средней дистанции.", fr: "Travail des tirs à mi-distance.", en: "Mid-range shooting practice." },
  },
  {
    id: "r2",
    date: "2026-07-28",
    group: { ru: "Футбол — соревновательный", fr: "Football — compétition", en: "Football — competitive" },
    present: 22,
    absent: 0,
    notes: { ru: "Полный состав, тактическая подготовка к матчу.", fr: "Effectif complet, préparation tactique du match.", en: "Full squad, match tactics preparation." },
  },
  {
    id: "r3",
    date: "2026-07-29",
    group: { ru: "Плавание — группа 1", fr: "Natation — groupe 1", en: "Swimming — group 1" },
    present: 11,
    absent: 1,
    notes: { ru: "Отработка поворотов и стартового прыжка.", fr: "Travail des virages et du plongeon de départ.", en: "Turning and start dive practice." },
  },
  {
    id: "r4",
    date: "2026-07-30",
    group: { ru: "Пауэрлифтинг — основы", fr: "Powerlifting — bases", en: "Powerlifting — basics" },
    present: 8,
    absent: 1,
    notes: { ru: "Техника приседания, работа с лёгким весом.", fr: "Technique du squat, travail léger.", en: "Squat technique with light weights." },
  },
];
